### ISSUE TITLE
Settings (pre-scaler, etc) for more resilient, low-bandwith, long range PLC

### ISSUE THREAD

**Issue by netadair** [qca/open-plc-utils#126]
Hi all,

not exactly an issue with the software, but merely a question if someone did elaborate (and maybe successfully) implement setting for PLC adapters to be more resilitent on bad line conditions, or have some ideas for me to test :)
Read: long cable lengths (including thick wire sizes of 16mm² or 25mm²), high attenuation , etc. 
This of cause at the cost of (significantly) reduced bandwith; I prefer stable 10mbps or less over instable and flapping 300mbps ... 

BR
Michael

**Comment by n1000** [comment]
Closing stale issues that are not directly related to a bug in open-plc-utils.
