### ISSUE TITLE
Cloning flash?

### ISSUE THREAD

**Issue by typhoon2099** [qca/open-plc-utils#136]
Is it possible to read the entire flash contents of one device to put onto another device? I have bricked devices and it just occurred o me that if I could get a working device and dump the entire flash memory to flash directly onto another device I could get it up and running again to then flash the correct NVM/PIB (currently not possible as I don't have a softloader and nobody seems to have one to give me).

**Comment by HimanshuSourav** [comment]
Is it possible to read the entire flash contents of one device - YES
using plcinit option o
` -o f   read all of flash memory using VS_MODULE_OPERATION`
put onto another device?  - Not with the toolkit yet. but if u can take out the flash chip and use the flash programmer -YES

but yeah sounds like a good idea though...

**Comment by n1000** [comment]
Closing stale issues that are not directly related to a bug in open-plc-utils.
