### ISSUE TITLE
qca7000 Firmware versions & Firmware parser development

### ISSUE THREAD

**Issue by boraciner** [qca/open-plc-utils#137]
Hi everyone, I want to develop a parser for the firmware of qca7000. Attached files are extracted from 1.2.5 version which I only have as a firmware file
[files](https://drive.google.com/drive/folders/131ivjvbIQphllXZ8SprPil2G9pAJMAE1?usp=sharing)

I need to parse/understand the contents of block NVM_IMAGE_FIRMWARE do you have any idea?
Do you have different firmware versions for qca7000 ? 

Thanks!

**Comment by specialistvlad** [comment]
@boraciner could you provide firmware again? Can't download it

**Comment by zgb526642524** [comment]
@boraciner Currently I have firmware with version number 3.1.0

**Comment by boraciner** [comment]
Can you share firmware version number 3.1.0 with me ?

**Comment by boraciner** [comment]
not needed

**Comment by oliviermaridat** [comment]
Hi boraciner. Did you manage the qca7000 firmware using another tool? I am curious!

**Comment by boraciner** [comment]
unfortunately not

**Comment by Petcho2207** [comment]
Hello everyone,

I am a university student at KMUTNB in Thailand. I am currently working on a project involving communication between an electric vehicle (EV) and a charger using Power Line Communication (PLC). For this project, I am using the QCA7000 chip, and I need a firmware version higher than v1.0.0-07. Could you please share the firmware with me?

Thank you very much.

**Comment by mhei** [comment]
@Petcho2207: it is very uncool to post randomly at closed issues.
But for your information, the firmware is usally available only under NDA with QCA, but you could have a look here: https://github.com/devolo/dlan-greenphy-sdk/tree/master/QCA7000_GreenPHY_Firmware

**Comment by e-music** [comment]
The link is not valid anymore. I was wondering if someone could share the latest FW version here. I need it, too!
