### ISSUE TITLE
QCA7005 SPI response error

### ISSUE THREAD

**Issue by 1tianmaxingkong1** [qca/open-plc-utils#144]
When using the Raspberry Pi to check the status of QCA7000 for the first time, QCA7000 returned an error status of 0x5A. The access and response messages are as follows:
MOSI: 0xDA 0x00 0x00 0x00 0xDA 0x00 0x00 0x00
MISO: 0x00 0x00 0x00 0x00 0x5A 0xD6 0xD6 0xD6

Does anyone encounter similar questions? What does 0x5A mean and is there a solution?

**Comment by ch-aurich** [comment]
We have seen similar things when connecting the SPI directly. What helped was to put 10 Ohm series  resistors in each SPI line. MISO, MOSI, CS and CLK

Am 22. Januar 2021 09:11:31 MEZ schrieb 1tianmaxingkong1 <notifications@github.com>:
>When using the Raspberry Pi to check the status of QCA7000 for the
>first time, QCA7000 returned an error status of 0x5A. The access and
>response messages are as follows:
>MOSI: 0xDA 0x00 0x00 0x00 0xDA 0x00 0x00 0x00
>MISO: 0x00 0x00 0x00 0x00 0x5A 0xD6 0xD6 0xD6
>
>Does anyone encounter similar questions? What does 0x5A mean and is
>there a solution?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/qca/open-plc-utils/issues/144

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by 1tianmaxingkong1** [comment]
Glad to receive your reply, it is really helpful to us, thank you again.
