### ISSUE TITLE
SLAC folder don't compile

### ISSUE THREAD

**Issue by amolina-chargevite** [qca/open-plc-utils#160]
Hi,

I am using OSRQCA-929 tag and I obtain the next fail when I try compile the slac folder:

![imagen](https://user-images.githubusercontent.com/100688696/167380580-693df02c-3695-4a2d-90d6-a427e6d8926d.png)

I have also tried with the https://github.com/mhei/open-plc-utils/tree/OSRQCA-929 repository and I have the same problem. I have achieved compile with the master branch, so I don't understand which ocurrs.

Thanks in advance.

**Comment by n1000** [comment]
Commit 003bfe04a1e90c004506c12cba9dc61ef415726b fixes this issue.
