### ISSUE TITLE
PLCID comes back with an error if an earlier device is on the ethernet network 

### ISSUE THREAD

**Issue by ajdel** [qca/open-plc-utils#18]
hey there,

I was wondering if you could look at a bug where if you have a 74XX device which you want to query with PLCid you usually get back the details id the Device that the command can see. However if there is a 64XX chipset based device and its attached via     ethernet the result returned is an error.

**Comment by n1000** [comment]
It sounds like the original issue was resolved. Please create a new issue if you are still having problems with other tools.
