### ISSUE TITLE
plcID sends in a endless loop

### ISSUE THREAD

**Issue by lategoodbye** [qca/open-plc-utils#23]
In the case no powerline device is connected, plcID sends request messages in a endless loop.

```
./plc/plcID -i eth0 -v
```

Output:

00000000 00 B0 52 00 00 01 00 48 54 6E 1F 6A 88 E1 00 00 ..R....HTn.j....
00000010 A0 00 B0 52 00 00 00 00 00 00 00 00 00 00 00 00 ...R............
00000020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00000030 00 00 00 00 00 00 00 00 00 00 00 00             ............    

00000000 00 B0 52 00 00 01 00 48 54 6E 1F 6A 88 E1 00 00 ..R....HTn.j....
00000010 A0 00 B0 52 00 00 00 00 00 00 00 00 00 00 00 00 ...R............
00000020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00000030 00 00 00 00 00 00 00 00 00 00 00 00             ............    

...

Expected behavior:

plcID terminate because of timeout

**Comment by n1000** [comment]
Commit 8c47ccef5e415492c8146c6e6df3a6ba39c99f95 added support for a custom timeout with the -t option. Using this, the retry rate on the VS_SW_VER can be controlled. Closing this one for now...
