### ISSUE TITLE
Bad checksum after saving PIB file with Avitar

### ISSUE THREAD

**Issue by lategoodbye** [qca/open-plc-utils#26]
open-plc-utils are unable to handle QCA7000 pib files saved with Avitar 1.1.0.727. Tools like modpib or plctool report a checksum error.

As an important note, the file size of the pib file is reduced after saving with Avitar:
user.pib (original pib) - 9328 bytes
user2.pib (avitar pib) - 9040 bytes

Steps to reproduce:
- Upload pib file from QCA7000

    plctool -i qca0 -p user.pib local

- Open PIB with the name "user.pib" with Avitar 1.1.0.727
- Save PIB with the name "user2.pib"
- Check PIB file with modpib

    modpib -v user2.pib

Output

modpib: pibchain2 found bad image checksum in user2.pib module 0

**Comment by n1000** [comment]
Have you been able to test with a more recent version of Avitar? Please reopen if this is still an issue.
