### ISSUE TITLE
Clarification on qca7420

### ISSUE THREAD

**Issue by ottuzzi** [qca/open-plc-utils#32]
Hi there,

from documentation is not clear to me how to flash a qca7420: I simply want to update/upgrade running firmware.
It looks like int6k is for updating intellon chipset (6300/6400), plcboot supports qca7420 but it looks like it is only for bootstrapping.
What command do I have to use to update/upgrade flash for an already running qca7420?

Many thanks
Bye
Piero

**Comment by n1000** [comment]
It looks like this question has been answered, closing. Please reopen if there are still issues.
