### ISSUE TITLE
error: ‘struct plc’ has no member named ‘SFT’

### ISSUE THREAD

**Issue by lategoodbye** [qca/open-plc-utils#37]
Compiling the current master leads to the following error:

    gcc -c FlashDevice2.c -Wall -Wextra -Wno-unused-parameter -DMAKEFILE -D__GETOPT_H__ -D_GETOPT_DEFINED_  -DAR7x00 
    FlashDevice2.c: In function ‘FlashDevice2’:
    FlashDevice2.c:65:9: error: ‘struct plc’ has no member named ‘SFT’

I think there are some missing changes in commit 14905f6228b3c7773e089af36ba810eb48d896a2.

**Comment by razzlefratz** [comment]
That is an effective workaround. This error was caused because the virgin chipsets need a soft loader file in addition a .pib and .nvm file.  We missed some references. Please see the latest plc.h header for the correct solution which looks something like yours. Thanks.
