### ISSUE TITLE
RTS/CTS and contention window

### ISSUE THREAD

**Issue by christinavl** [qca/open-plc-utils#39]
Hello,

I would like to enable the RTS/CTS mechanism on either chips INT6300 or AR7420.
I would also like to modify the contention window of the MAC protocol. 
Do you know if I could modify the above with the open-plc-utils?
Thank you very much in advance!

Best,
Christina

**Comment by razzlefratz** [comment]
Hi Christina,

I will be closing this issue soon, if that is OK with you.

**Comment by christinavl** [comment]
Yes, sure. Thanks.
