### ISSUE TITLE
Support for Broadcom HomePlug chipsets?

### ISSUE THREAD

**Issue by shmerl** [qca/open-plc-utils#67]
Sorry if it's a wrong place to post this. Does open-plc-utils support Broadcom chipset based HomePlug adapters like ZyXEL PLA5456KIT HomePlug AV2? And if not, are there any plans to add such support?

**Comment by n1000** [comment]
open-plc-utils mainly focuses on Qualcomm Atheros Vendor Specific Management Messages. As far as I know there are no plans to add Broadcom chipset support to this project.

**Comment by lategoodbye** [comment]
@shmerl AFAIK there is no public documentation about the BCM60500 so it would be very hard to implement.

**Comment by n1000** [comment]
Closing this for now, we could reconsider this if the vendor specific MME information is released publicly.

**Comment by mirh** [comment]
https://github.com/serock/pla-util
