### ISSUE TITLE
Windows version of the toolkit is missing?

### ISSUE THREAD

**Issue by Martin-P** [qca/open-plc-utils#72]
Hi all,

The docbook says the following in the chapter [Toolkit Installation on Windows 7™](https://github.com/qca/open-plc-utils/blob/9ddb713cc0ad5ce496c9e46e671133e364377b41/docbook/ch01s07.html#L8):

> The Windows™ version of the toolkit comes pre-compiled and ready to install and run using the native Windows Installer. You may copy and distribute installation file plc-utils-x.x.x.msi.

Can you please tell me where I can find these files? There are some references to FTP locations, but none of those work (anymore).

**Comment by lategoodbye** [comment]
Hi @Martin-P,
the open-plc-utils doesn't have a Windows Installer, only the closed source variant has. This documentation issue needs to be fixed.

**Comment by Martin-P** [comment]
Thanks for the info @lategoodbye,
do you know where I can find more detailed information about the closed source variant? I [searched](https://www.google.nl/search?q=site:www.qualcomm.com+powerline+toolkit) the Qualcomm site and unfortunately can't find any info about a powerline toolkit.

**Comment by ch-aurich** [comment]
AFAIK the powerline toolkit is only available from Qualcomm under NDA, please contact you local sales rep if you need more information.

**Comment by lategoodbye** [comment]
Btw It's possible to compile most of the tools with Visual Studio Community 2015.

**Comment by Martin-P** [comment]
Thanks @ch-aurich and @lategoodbye for your help and info!
